-- Saaya Traits with Monopoly Mode active
INSERT INTO TraitModifiers
(TraitType, ModifierId)
VALUES
('TRAIT_LEADER_SAAYA_gkls621',  'SAAYA_PROJECT_BAKING_gkls621'),
('TRAIT_LEADER_SAAYA_gkls621',  'SAAYA_GRANARY_PRODUCT_SLOT_gkls621'),
('TRAIT_LEADER_SAAYA_gkls621',  'SAAYA_GRANARY_AUTO_THEMED_gkls621');

INSERT INTO Modifiers
(ModifierId,    ModifierType,   SubjectRequirementSetId)
VALUES
('SAAYA_GRANARY_PRODUCT_SLOT_gkls621',  'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_GREAT_WORK_SLOTS',    NULL),
('SAAYA_PROJECT_BAKING_gkls621',    'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',  'REQSET_PPP_WHEAT_IMPROVED_gkls621'),
('SAAYA_GRANARY_AUTO_THEMED_gkls621',   'MODIFIER_PLAYER_ADJUST_AUTO_THEMED_BUILDING',    NULL);

INSERT INTO ModifierArguments
(ModifierId,    Name,   Value)
VALUES
('SAAYA_PROJECT_BAKING_gkls621',    'ProjectType', 'PROJECT_CREATE_PRODUCT_BREAD_gkls621'),
('SAAYA_GRANARY_PRODUCT_SLOT_gkls621', 'Amount', 3),
('SAAYA_GRANARY_PRODUCT_SLOT_gkls621', 'BuildingType', 'BUILDING_GRANARY'),
('SAAYA_GRANARY_PRODUCT_SLOT_gkls621', 'GreatWorkSlotType', 'GREATWORKSLOT_PRODUCT'),
('SAAYA_GRANARY_AUTO_THEMED_gkls621',  'BuildingType', 'BUILDING_GRANARY');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES
('REQSET_PPP_WHEAT_IMPROVED_gkls621', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES
('REQSET_PPP_WHEAT_IMPROVED_gkls621', 'PPP_WHEAT_IMPROVED_gkls621');

INSERT INTO Requirements (RequirementId, RequirementType)
VALUES
('PPP_WHEAT_IMPROVED_gkls621', 'REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES
('PPP_WHEAT_IMPROVED_gkls621', 'ResourceType', 'RESOURCE_WHEAT');