-- Poppin' Party Civilisation

INSERT INTO Types
(Type,  Kind)
VALUES
('CIVILIZATION_PPP_gkls621',    'KIND_CIVILIZATION');

INSERT INTO Civilizations
(CivilizationType,  Name,   Description,    Adjective,  StartingCivilizationLevelType,    Ethnicity)
VALUES
('CIVILIZATION_PPP_gkls621',    'LOC_CIVILIZATION_PPP_gkls621_NAME',    'LOC_CIVILIZATION_PPP_gkls621_DESCRIPTION', 'LOC_CIVILIZATION_PPP_gkls621_ADJECTIVE',   'CIVILIZATION_LEVEL_FULL_CIV',  'ETHNICITY_ASIAN');

INSERT INTO CivilizationLeaders
(CivilizationType,              LeaderType,                 CapitalName)
VALUES
('CIVILIZATION_PPP_gkls621',    'LEADER_KASUMI_gkls621',    'LOC_CIVILIZATION_PPP_gkls621_CITY_1'),
('CIVILIZATION_PPP_gkls621',    'LEADER_ARISA_gkls621',     'LOC_CIVILIZATION_PPP_gkls621_CITY_2'),
('CIVILIZATION_PPP_gkls621',    'LEADER_TAE_gkls621',       'LOC_CIVILIZATION_PPP_gkls621_CITY_3'),
('CIVILIZATION_PPP_gkls621',    'LEADER_SAAYA_gkls621',     'LOC_CIVILIZATION_PPP_gkls621_CITY_4'),
('CIVILIZATION_PPP_gkls621',    'LEADER_RIMI_gkls621',      'LOC_CIVILIZATION_PPP_gkls621_CITY_5');

INSERT INTO CityNames	
(CivilizationType,              CityName)	
VALUES
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_1'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_2'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_3'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_4'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_5'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_6'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_7'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_8'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_9'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_10'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_11'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_12'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_13'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_14'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_15'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_16'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_17'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_18'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_19'),
('CIVILIZATION_PPP_gkls621',	'LOC_CIVILIZATION_PPP_gkls621_CITY_20');

INSERT INTO CityNames	
(CivilizationType,              CityName)	
SELECT  'CIVILIZATION_PPP_gkls621', CityName
FROM CityNames WHERE CivilizationType = 'CIVILIZATION_JAPAN';

INSERT INTO CivilizationCitizenNames
(CivilizationType,              CitizenName,                    Female)
VALUES
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_1',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_2',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_3',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_4',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_5',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_6',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_7',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_8',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_9',    1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_10',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_11',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_12',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_13',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_14',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_15',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_16',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_17',   1),
('CIVILIZATION_PPP_gkls621',    'LOC_CITIZEN_PPP_gkls621_18',   1);

INSERT INTO CivilizationCitizenNames
(CivilizationType,              CitizenName,                    Female)
SELECT 'CIVILIZATION_PPP_gkls621',  CitizenName,    1
FROM CivilizationCitizenNames  WHERE CivilizationType = 'CIVILIZATION_JAPAN' AND Female = 1;

INSERT INTO CivilizationInfo
(CivilizationType,  Header, Caption)
VALUES
('CIVILIZATION_PPP_gkls621',    'LOC_CIVINFO_LOCATION',     'LOC_CIVINFO_PPP_gkls621_LOCATION'),
('CIVILIZATION_PPP_gkls621',    'LOC_CIVINFO_SIZE',         'LOC_CIVINFO_PPP_gkls621_SIZE'),
('CIVILIZATION_PPP_gkls621',    'LOC_CIVINFO_POPULATION',   'LOC_CIVINFO_PPP_gkls621_POPULATION'),
('CIVILIZATION_PPP_gkls621',    'LOC_CIVINFO_CAPITAL',      'LOC_CIVINFO_PPP_gkls621_CAPITAL');

-- The starting plot bias
INSERT INTO StartBiasResources
(CivilizationType,  ResourceType,    Tier)
SELECT 'CIVILIZATION_PPP_gkls621', ResourceType, 1
FROM Improvement_ValidResources WHERE ImprovementType = 'IMPROVEMENT_MINE';

INSERT INTO StartBiasFeatures
(CivilizationType,  FeatureType,    Tier)
VALUES
('CIVILIZATION_PPP_gkls621',    'FEATURE_FOREST',   3);