-- Config Adjustment when Light Industrial Zone is on
UPDATE PlayerItems
SET Type = 'DISTRICT_YAMABUKI_BAKERY_gkls621'
WHERE LeaderType = 'LEADER_SAAYA_gkls621' AND SortIndex = 30
AND EXISTS(SELECT 1 FROM PlayerItems WHERE Type = 'BUILDING_CHINA_LDA2');

UPDATE PlayerItems
SET Name = 'LOC_DISTRICT_YAMABUKI_BAKERY_gkls621_NAME'
WHERE LeaderType = 'LEADER_SAAYA_gkls621' AND SortIndex = 30
AND EXISTS(SELECT 1 FROM PlayerItems WHERE Type = 'BUILDING_CHINA_LDA2');

UPDATE PlayerItems
SET Description = 'LOC_DISTRICT_YAMABUKI_BAKERY_gkls621_DESCRIPTION'
WHERE LeaderType = 'LEADER_SAAYA_gkls621' AND SortIndex = 30
AND EXISTS(SELECT 1 FROM PlayerItems WHERE Type = 'BUILDING_CHINA_LDA2');

UPDATE PlayerItems
SET Icon = 'ICON_DISTRICT_YAMABUKI_BAKERY_gkls621'
WHERE LeaderType = 'LEADER_SAAYA_gkls621' AND SortIndex = 30
AND EXISTS(SELECT 1 FROM PlayerItems WHERE Type = 'BUILDING_CHINA_LDA2');
